### ISSUE TITLE
Kinesis Data Streams support

### ISSUE THREAD

**Issue by mumoshu** [s12v/awsbeats#5]
@s12v Hi! Thank you very much for sharing an awesome plugin 👍 

I was just looking into the code-base of this plugin, and realized that it supports Kinesis Firehose only.

Would you mind if I contribute a support for Kinesis Data Streams?
I believe it makes sense for this project to contain supports for both, like the fluentd-equivalent of this plugin [aws-fluent-plugin-kinesis](https://github.com/awslabs/aws-fluent-plugin-kinesis) does.

**Comment by s12v** [comment]
@mumoshu, sure, makes a lot of sense

**Comment by mumoshu** [comment]
@s12v Thanks for the confirmation! Just submitted #7 for this.
