### ISSUE TITLE
Suggestion for renaming

### ISSUE THREAD

**Issue by mumoshu** [s12v/awsbeats#8]
How about renaming to `kinesisbeats` or even `kinesisbeat` so that it is clearer that this project covers aws kinesis sub-services only?

**Comment by mumoshu** [comment]
@s12v I guess, perhaps you wanted to cover other backends like Lambda functions and/or CloudWatch logs, events? If that's why you name this `awsbeats` - makes sense for me.

**Comment by s12v** [comment]
@mumoshu, yes, exactly :)

**Comment by mumoshu** [comment]
@s12v Sounds good! Closing as this isn't an issue then.

Btw, which one do you like to pick next?
